import XCTest
@testable import Podium

/// The strongest verification a machine-code generator can get: actually
/// allocate executable memory, run the generated bytes on the real CPU,
/// and check the result — not just that the encoder produced *some*
/// plausible-looking word. Skips (rather than fails) when the process
/// doesn't hold the dynamic-codesigning right `mprotect(PROT_EXEC)`
/// needs (no entitlement, no debugger attached), since that's an
/// expected, documented platform outcome on iOS (see
/// `ExecutableMemoryAllocator`), not something these tests exist to
/// catch — on a plain local macOS run, this right is available with no
/// extra setup, so these actually exercise the JIT rather than skip.
final class JITExecutionTests: XCTestCase {
    private func mov(rd: Int, imm: UInt32) -> DataProcessingInstruction {
        DataProcessingInstruction(condition: .always, op: .mov, setFlags: false, rn: 0, rd: rd, operand2: .immediate(value: imm, forcedCarryOut: nil))
    }

    private func addOrSub(_ op: DataProcessingOp, rd: Int, rn: Int, rm: Int) -> DataProcessingInstruction {
        DataProcessingInstruction(condition: .always, op: op, setFlags: false, rn: rn, rd: rd, operand2: .shiftedRegister(rm: rm, shiftType: .lsl, shiftAmount: 0))
    }

    func testCompiledAdditionMatchesHandComputedResult() throws {
        let instructions = [mov(rd: 0, imm: 5), mov(rd: 1, imm: 3), addOrSub(.add, rd: 2, rn: 0, rm: 1)]
        guard let block = JITTranslator.translate(instructions) else {
            throw XCTSkip("Executable memory (mprotect PROT_EXEC) isn't available in this test environment.")
        }

        var registers = [UInt32](repeating: 0, count: 16)
        registers.withUnsafeMutableBufferPointer { block.run(registers: $0.baseAddress!) }

        XCTAssertEqual(registers[0], 5)
        XCTAssertEqual(registers[1], 3)
        XCTAssertEqual(registers[2], 8)
    }

    func testCompiledSubtractionMatchesHandComputedResult() throws {
        let instructions = [mov(rd: 0, imm: 10), mov(rd: 1, imm: 4), addOrSub(.sub, rd: 2, rn: 0, rm: 1)]
        guard let block = JITTranslator.translate(instructions) else {
            throw XCTSkip("Executable memory (mprotect PROT_EXEC) isn't available in this test environment.")
        }

        var registers = [UInt32](repeating: 0, count: 16)
        registers.withUnsafeMutableBufferPointer { block.run(registers: $0.baseAddress!) }

        XCTAssertEqual(registers[2], 6)
    }

    func testCompiledRegisterMovIsAPlainCopy() throws {
        let instructions = [
            mov(rd: 0, imm: 0xABCD),
            DataProcessingInstruction(condition: .always, op: .mov, setFlags: false, rn: 0, rd: 5, operand2: .shiftedRegister(rm: 0, shiftType: .lsl, shiftAmount: 0)),
        ]
        guard let block = JITTranslator.translate(instructions) else {
            throw XCTSkip("Executable memory (mprotect PROT_EXEC) isn't available in this test environment.")
        }

        var registers = [UInt32](repeating: 0, count: 16)
        registers.withUnsafeMutableBufferPointer { block.run(registers: $0.baseAddress!) }

        XCTAssertEqual(registers[5], 0xABCD)
    }

    /// Runs the same program through a pure-interpreter CPU and a
    /// JIT-enabled CPU, and requires them to agree exactly. Comparing
    /// against the interpreter (already verified independently in
    /// `ARMv7CPUTests`) catches the JIT computing a *different* answer,
    /// which is the failure mode hand-written code generation is
    /// actually at risk of — a hand-computed expected value here would
    /// only re-check my own arithmetic, not cross-check it.
    func testJITEnabledCPUMatchesInterpreterOverAFullRun() throws {
        let program: [UInt32] = [
            0xE3A0_0005, // MOV r0, #5
            0xE3A0_1003, // MOV r1, #3
            0xE080_2001, // ADD r2, r0, r1
            0xE040_3001, // SUB r3, r0, r1
        ]

        let interpreterMemory = FlatPhysicalMemory(length: 64)
        for (index, word) in program.enumerated() {
            try interpreterMemory.writeWord32(word, at: UInt32(index * 4))
        }
        let interpreterCPU = ARMv7CPU(memory: interpreterMemory)
        interpreterCPU.reset()
        for _ in program { interpreterCPU.step() }

        let jitMemory = FlatPhysicalMemory(length: 64)
        for (index, word) in program.enumerated() {
            try jitMemory.writeWord32(word, at: UInt32(index * 4))
        }
        let jitEngine = JITEngine()
        let jitCPU = ARMv7CPU(memory: jitMemory, jit: jitEngine)
        jitCPU.reset()
        jitCPU.run()

        guard jitEngine.stats.compiledBlockCount > 0 else {
            throw XCTSkip("JIT produced no compiled blocks in this environment (mprotect PROT_EXEC unavailable).")
        }

        XCTAssertNil(jitCPU.lastError)
        for register in 0..<4 {
            XCTAssertEqual(jitCPU.registers[register], interpreterCPU.registers[register], "register \(register) diverged between JIT and interpreter")
        }
        XCTAssertEqual(jitCPU.registers.pc, interpreterCPU.registers.pc)
    }

    /// `JITEngine`/`JITTranslator` only ever decode/compile ARM-state
    /// `DataProcessingInstruction`s (see `JITEngine.discoverEligibleRun`'s
    /// doc comment) — `ARMv7CPU.runOneUnit()` must never even attempt the
    /// JIT while the CPU is actually in Thumb state, or it would
    /// misinterpret real Thumb instruction bytes as a completely
    /// different ARM-state word. This was a latent bug masked by
    /// `ExecutableMemoryAllocator` always failing (every attempt fell
    /// back to the interpreter regardless); fixed alongside that
    /// allocator fix, since fixing allocation alone would otherwise have
    /// turned this into a live silent-miscompilation risk. Uses the exact
    /// same word (`0xE3A00005`, "MOV r0, #5") the other tests in this
    /// file prove *is* genuinely JIT-eligible in ARM state, so this only
    /// passes if the Thumb-state check is what's stopping it, not some
    /// unrelated ineligibility.
    func testJITNeverAttemptedWhileCPUIsInThumbState() throws {
        let memory = FlatPhysicalMemory(length: 16)
        try memory.writeWord32(0xE3A0_0005, at: 0)

        let jitEngine = JITEngine()
        let cpu = ARMv7CPU(memory: memory, jit: jitEngine)
        cpu.reset()
        cpu.cpsr.thumbState = true
        _ = cpu.run(maxUnits: 1)

        XCTAssertEqual(jitEngine.stats, JITEngine.Stats())
    }
}
