#!/bin/zsh
# Builds first_boot_capture for the guest (armv7, iOS 6); see
# ../keybag_bootstrap/build.sh for why it's built and signed this way.
# Each build generates a new stand-in activation identity (a 1024-bit RSA
# key and a self-signed certificate for it) into identity.h.
# Usage: build.sh <output>
set -e
cd "$(dirname "$0")"
OUT=${1:-/tmp/first_boot_capture}
TMP=$(mktemp -d)
openssl genrsa -traditional -out "$TMP/key.pem" 1024 2>/dev/null || openssl genrsa -out "$TMP/key.pem" 1024
openssl rsa -in "$TMP/key.pem" -traditional -outform DER -out "$TMP/key.der" 2>/dev/null || openssl rsa -in "$TMP/key.pem" -outform DER -out "$TMP/key.der"
openssl req -new -x509 -key "$TMP/key.pem" -sha1 -days 7300 -subj "/CN=Podium Activation Identity" -outform DER -out "$TMP/certificate.der"
{
    echo "// Generated by build.sh: the stand-in activation identity."
    echo "static const unsigned char activation_key_der[] = {"
    xxd -i < "$TMP/key.der"
    echo "};"
    echo "static const unsigned char activation_certificate_der[] = {"
    xxd -i < "$TMP/certificate.der"
    echo "};"
} > "$TMP/identity.h"
xcrun --sdk iphoneos clang -target armv7-apple-ios6.0 -marm -Os -fno-stack-protector -I "$TMP" -c first_boot_capture.c -o "$TMP/capture.o"
xcrun ld -arch armv7 -platform_version ios 6.0 6.0 -e _main "$TMP/capture.o" libSystem.tbd CoreFoundation.tbd Security.tbd -o "$TMP/capture.unsigned"
xcrun codesign_allocate -i "$TMP/capture.unsigned" -a armv7 4096 -o "$TMP/capture"
python3 ../keybag_bootstrap/legacy_adhoc_sign.py "$TMP/capture" com.podium.first_boot_capture entitlements.plist
cp "$TMP/capture" "$OUT"
rm -rf "$TMP"
echo "wrote $OUT"
